data:
  file_path: "data/sample_data.csv"
  target_column: "Failure_Flag"

model:
  type: "RandomForestClassifier"
  saved_model_path: "predictive_model.pkl"

visualization:
  dashboard_tool: "Power BI"
  metrics_to_display:
    - Temperature
    - Vibration
    - Speed
    - Runtime
    - Failure Prediction

alerts:
  enable: true
  threshold_temperature: 80
  threshold_vibration: 5.0
